### ISSUE TITLE
android.view.InflateException: Binary XML file line #73: Error inflating class com.maksim88.passwordedittext.PasswordEditText

### ISSUE THREAD

**Issue by ericntd** [maksim88/PasswordEditText#11]
I went in and check your PasswordEditText class. It imports `import android.support.design.widget.TextInputEditText;` which is not resolvable. I thought it's supposed to be `android.support.design.widget.TextInputEditText` instead?

More of the stacktrace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 android.view.InflateException: Binary XML file line #73: Error inflating class com.maksim88.passwordedittext.PasswordEditText
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
```

**Comment by maksim88** [comment]
What is exactly the difference between your paths of TextInputEditText? I see the same one printed twice
I checked once again and the right one is imported (https://developer.android.com/reference/android/support/design/widget/TextInputEditText.html)
so: `android.support.design.widget.TextInputEditText`

Could it be an issue with Calligraphy or the connection of both libs? The log that you posted 
indicated it in the second to last line `at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)`
I just tested it a little bit with a small project and calligraphy works fine for me.

Can you also give more information about the device, system, lib version etc?
And maybe put the whole xml of `PasswordEditText` or a small reproducible example where it happens together because i cannot reproduce it on my side.

**Comment by ericntd** [comment]
Sorry my bad on the class difference. They are the same.
Anyway, I've tried using another library and it works for me.

Thanks.

Following is the fragment layout I tried to inflate btw, if it can help you to replicate the issue:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:focusable="true"
              android:focusableInTouchMode="true"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
    <!-- Login progress -->
    <ProgressBar
        android:id="@+id/login_progress"
        style="?android:attr/progressBarStyleLarge"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginBottom="8dp"
        android:visibility="gone"/>

    <ScrollView
        android:id="@+id/login_form"
        android:focusable="true"
        android:focusableInTouchMode="true"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white">

        <LinearLayout
            android:id="@+id/layoutLogin"
            android:focusable="true"
            android:focusableInTouchMode="true"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:paddingTop="@dimen/activity_vertical_margin"
            android:paddingLeft="@dimen/activity_horizontal_margin"
            android:paddingRight="@dimen/activity_horizontal_margin"
            android:background="@android:color/white">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:padding="@dimen/padding_fragment_sm"
                android:text=""
                android:visibility="gone"
                android:id="@+id/message"
                android:layout_gravity="center_horizontal"/>

            <android.support.design.widget.TextInputLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <AutoCompleteTextView
                    android:id="@+id/email"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:hint="@string/prompt_email"
                    android:inputType="textEmailAddress"
                    android:maxLines="1"
                    android:singleLine="true"/>

            </android.support.design.widget.TextInputLayout>

            <android.support.design.widget.TextInputLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                <com.maksim88.passwordedittext.PasswordEditText
                    android:id="@+id/password"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:hint="@string/prompt_password"
                    android:inputType="textPassword"
                    android:maxLines="1"
                    android:singleLine="true"/>

            </android.support.design.widget.TextInputLayout>
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:paddingTop="@dimen/activity_vertical_margin">
                <View
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="0.25"/>
                <Button
                    android:id="@+id/email_sign_in_button"
                    style="@style/AppTheme.Button.WhiteOnBlack"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="0.5"
                    android:text="@string/action_sign_in_short" />
                <View
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="0.25"/>
            </LinearLayout>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="@dimen/margin_double"
                android:text="@string/forgot_password_link"
                android:id="@+id/linkForgotPassword"
                android:layout_gravity="center_horizontal"/>

        </LinearLayout>
    </ScrollView>
</LinearLayout>
```

**Comment by maksim88** [comment]
Hmm sorry, but I tried the same layout in a new project and it worked fine for me. No InflateExceptions.
