### ISSUE TITLE
This library is causing Rendering problem. 

### ISSUE THREAD

**Issue by Anandsoni14** [maksim88/PasswordEditText#17]
When I first used it, it was ok but now, it creating a problem in Rendering.
First I thought it might be problem In Studio 2.3 beta version. But after debugging it more, I got the issue.
As I removed this lib. everything works fine now. I think there must be some issue in library. Please check it.

**Comment by maksim88** [comment]
Can you be more specific? What is the rendering issue exactly?

**Comment by Anandsoni14** [comment]
```

Rendering failed with a known bug. Please try a rebuild.  The following classes could not be instantiated:
- android.support.design.widget.TabLayout (Open Class, Show Exception, Clear Cache)
- android.support.design.widget.CoordinatorLayout (Open Class, Show Exception, Clear Cache)
- android.support.design.widget.AppBarLayout (Open Class, Show Exception, Clear Cache)
- android.support.design.widget.FloatingActionButton (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.Toolbar (Open Class, Show Exception, Clear Cache)
- android.support.constraint.ConstraintLayout (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.
  Exception Details java.lang.NoSuchFieldError: TabLayout   at android.support.design.widget.TabLayout.<init>(TabLayout.java:307)   at android.support.design.widget.TabLayout.<init>(TabLayout.java:291)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
```

**Comment by maksim88** [comment]
I don't see any instances of my library in this stacktrace.

Did you try to invalidate caches and restart studio?

**Comment by Anandsoni14** [comment]
Yes! In fact I tried to change themes also, but none seems to worked, but as I removed this lib. Everything works normal.

**Comment by maksim88** [comment]
You sure that it wasn't just a coincidence because you did a full rebuild when you removed the library? 
Anyway, I can help you only if you provide me with a sample project or something I can play around to find out whether there is a problem. This is just not enough information to do sth.

**Comment by dannycodes8** [comment]
am also facing the same issue.......I need some help
